/**
 * Holds a DummyAPI model for comments
 * Please, note that this does not inherit our object model
 */
class Comment {
	id = ''; //: string(autogenerated)
	message = ''; //: string(length: 2-500)
	owner = {}; //: object(User Preview)
	post = ''; //: string(Post Id)
	publishDate = null; //: string(autogenerated)
}

export default Comment;
